/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.DaoLocacaoVeiculo;
import fatec.poo.control.PreparaConexao;
import fatec.poo.model.LocacaoVeiculo;
import java.text.DecimalFormat;

/**
 *
 * @author teusi
 */
public class LocacaoVeiculoGui extends javax.swing.JFrame {

    /**
     * Creates new form LocacaoVeiculoGui
     */
    public LocacaoVeiculoGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgrpTipoCliente = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNomeCliente = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rdbComum = new javax.swing.JRadioButton();
        rdbPremium = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtPlacaCarro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTaxaLocacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtValorKmRodado = new javax.swing.JTextField();
        lblValorLocacao = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnAlugar = new javax.swing.JButton();
        btnLiberar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtKmRodados = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Locação Veículo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Código da Locação");

        jLabel2.setText("Nome do Cliente");

        txtNomeCliente.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo do Cliente"));

        btgrpTipoCliente.add(rdbComum);
        rdbComum.setSelected(true);
        rdbComum.setText("Comum");
        rdbComum.setEnabled(false);

        btgrpTipoCliente.add(rdbPremium);
        rdbPremium.setText("Premium");
        rdbPremium.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rdbComum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbPremium)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbComum)
                    .addComponent(rdbPremium))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Placa do Carro");

        txtPlacaCarro.setEnabled(false);

        jLabel4.setText("Taxa de Locação(%)");

        txtTaxaLocacao.setEnabled(false);

        jLabel5.setText("Valor por Km rodado");

        txtValorKmRodado.setEnabled(false);

        lblValorLocacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setText("Valor da Locação");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnAlugar.setText("Alugar");
        btnAlugar.setEnabled(false);
        btnAlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlugarActionPerformed(evt);
            }
        });

        btnLiberar.setText("Liberar");
        btnLiberar.setEnabled(false);
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel7.setText("Km Rodados");

        txtKmRodados.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblValorLocacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPlacaCarro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txtTaxaLocacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txtValorKmRodado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKmRodados)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlugar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLiberar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPlacaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTaxaLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtValorKmRodado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtKmRodados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lblValorLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlugar)
                    .addComponent(btnLiberar)
                    .addComponent(btnSair))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        prepCon = new PreparaConexao("", "");
        prepCon.setDriver("net.ucanaccess.jdbc.UcanaccessDriver");
        prepCon.setConnectionString("jdbc:ucanaccess://C:\\Users\\Victorleonardo\\Documents\\NetBeansProjects\\prjTrab2PooMatheusLourencoVictorLeonardo\\src\\fatec\\poo\\basedados\\DB_POO.accdb");
        daoLocacaoVeiculo = new DaoLocacaoVeiculo(prepCon.abrirConexao());
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        prepCon.fecharConexao();
    }//GEN-LAST:event_formWindowClosed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        locacaoVeiculo = null;

        lblValorLocacao.setText(null);
        txtValorKmRodado.setText(null);
        txtKmRodados.setText(null);

        locacaoVeiculo = daoLocacaoVeiculo.consultar(Integer.parseInt(txtCodigo.getText())
        );

        if (locacaoVeiculo == null) {

            txtCodigo.setEnabled(false);

            txtNomeCliente.setEnabled(true);
            rdbComum.setEnabled(true);
            rdbPremium.setEnabled(true);
            txtPlacaCarro.setEnabled(true);
            txtTaxaLocacao.setEnabled(true);
            txtKmRodados.setEnabled(false);
            txtValorKmRodado.setEnabled(false);

            txtNomeCliente.requestFocus();

            btnConsultar.setEnabled(false);
            btnAlugar.setEnabled(true);
            btnLiberar.setEnabled(false);

        } else {

            txtNomeCliente.setText(locacaoVeiculo.getNomeCliente());

            if (locacaoVeiculo.getTipoCliente().equals("Comum")) {
                rdbComum.setSelected(true);
                rdbPremium.setSelected(false);
            } else {
                rdbPremium.setSelected(true);
                rdbComum.setSelected(false);
            }

            txtPlacaCarro.setText(locacaoVeiculo.getPlacaCarro());

            txtTaxaLocacao.setText(String.valueOf(locacaoVeiculo.getTaxaLocacao()));

            txtCodigo.setEnabled(false);
            txtNomeCliente.setEnabled(false);
            rdbComum.setEnabled(false);
            rdbPremium.setEnabled(false);
            txtPlacaCarro.setEnabled(false);
            txtTaxaLocacao.setEnabled(false);

            txtKmRodados.setEnabled(true);
            txtValorKmRodado.setEnabled(true);

            txtKmRodados.requestFocus();

            btnConsultar.setEnabled(false);
            btnAlugar.setEnabled(false);
            btnLiberar.setEnabled(true);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnAlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlugarActionPerformed
        locacaoVeiculo = new LocacaoVeiculo(
                Integer.parseInt(txtCodigo.getText()), txtNomeCliente.getText()
        );

        if (rdbComum.isSelected()) {
            locacaoVeiculo.setTipoCliente("Comum");
        } else {
            locacaoVeiculo.setTipoCliente("Premium");
        }

        locacaoVeiculo.setPlacaCarro(txtPlacaCarro.getText());

        locacaoVeiculo.setTaxaLocacao(Double.parseDouble(txtTaxaLocacao.getText())
        );

        daoLocacaoVeiculo.alugar(locacaoVeiculo);

        txtCodigo.setText(null);
        txtNomeCliente.setText(null);
        txtPlacaCarro.setText(null);
        txtTaxaLocacao.setText(null);
        txtValorKmRodado.setText(null);
        txtKmRodados.setText(null); 

        txtCodigo.setEnabled(true);
        txtNomeCliente.setEnabled(false);
        rdbComum.setEnabled(false);
        rdbPremium.setEnabled(false);
        txtPlacaCarro.setEnabled(false);
        txtTaxaLocacao.setEnabled(false);

        txtCodigo.requestFocus();

        txtValorKmRodado.setEnabled(true);
        txtKmRodados.setEnabled(true);

        btnAlugar.setEnabled(false);
        btnLiberar.setEnabled(true);
        btnConsultar.setEnabled(true);
    }//GEN-LAST:event_btnAlugarActionPerformed

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed
        DecimalFormat df = new DecimalFormat("#,###.##");

        locacaoVeiculo.setKmRodados(Integer.parseInt(txtKmRodados.getText())
        );

        double valorLocacao = locacaoVeiculo.calcValorPagar(
                Double.parseDouble(txtValorKmRodado.getText())
        );

        lblValorLocacao.setText(df.format(valorLocacao));

        daoLocacaoVeiculo.liberar(locacaoVeiculo);

        txtCodigo.setText(null);
        txtNomeCliente.setText(null);
        txtPlacaCarro.setText(null);
        txtTaxaLocacao.setText(null);
        txtKmRodados.setText(null);
        txtValorKmRodado.setText(null);

        txtCodigo.setEnabled(true);

        txtNomeCliente.setEnabled(false);
        rdbComum.setEnabled(false);
        rdbPremium.setEnabled(false);
        txtPlacaCarro.setEnabled(false);
        txtTaxaLocacao.setEnabled(false);
        txtKmRodados.setEnabled(false);
        txtValorKmRodado.setEnabled(false);

        btnConsultar.setEnabled(true);
        btnAlugar.setEnabled(false);
        btnLiberar.setEnabled(false);

        txtCodigo.requestFocus();
    }//GEN-LAST:event_btnLiberarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocacaoVeiculoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocacaoVeiculoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocacaoVeiculoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocacaoVeiculoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocacaoVeiculoGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgrpTipoCliente;
    private javax.swing.JButton btnAlugar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLiberar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblValorLocacao;
    private javax.swing.JRadioButton rdbComum;
    private javax.swing.JRadioButton rdbPremium;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtKmRodados;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtPlacaCarro;
    private javax.swing.JTextField txtTaxaLocacao;
    private javax.swing.JTextField txtValorKmRodado;
    // End of variables declaration//GEN-END:variables

    private LocacaoVeiculo locacaoVeiculo;
    private DaoLocacaoVeiculo daoLocacaoVeiculo;
    private PreparaConexao prepCon;
}
